
export const metadata = {
    title: 'Kanban',
    description: 'Generated by Next.js',
}

export default function RootLayout(props: {
    children: React.ReactNode,

}) {
    return (
        <>
            {props.children}
        </>
    )
}
